name: Update last200.csv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Update last200.csv
      run: |
        python your_script.py  # Replace with the actual script to update the CSV

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add last200.csv
        git commit -m "Update last200.csv" || echo "No changes to commit"
        git push
