name: Process Tunnel IPs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  process-csv:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pandas PyGithub

      - name: 处理CSV文件
        env:
          GITHUB_PERSONAL_TOKEN: ${{ secrets.EXTERNAL_REPO_TOKEN }}
        run: |
          python - <<EOF
          import pandas as pd
          import io
          from github import Github

          token = "${{ secrets.EXTERNAL_REPO_TOKEN }}"
          g = Github(token)

          repo = g.get_repo("x-dr/iptest")
          content = repo.get_contents("latest.csv").decoded_content.decode('utf-8')

          df = pd.read_csv(io.StringIO(content))
          tunnels = df[df["IP类型"].str.contains("隧道", na=False)].sort_values("等效带宽", ascending=False)
          tunnels.to_csv("last.csv", index=False, encoding="utf-8-sig")
          print("处理完成")
          EOF

      - name: 提交结果
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add last.csv
          git commit -m "Update last.csv"
          git push
